services:
  postgres:
    image: postgres:16
    container_name: markhet_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: markhet_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build  # :point_left: Use dev stage
    image: 050451360524.dkr.ecr.ap-south-1.amazonaws.com/markhet-server:latest
    container_name: markhet_server
    env_file:
      - .env.development
    command: pnpm start:dev  # :point_left: Run in watch mode
    ports:
      - '8001:8001'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    platform: linux/amd64
volumes:
  pgdata:
  redisdata:
