import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1753955588628 implements MigrationInterface {
    name = 'InitialMigration1753955588628'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_language_enum" AS ENUM('en', 'kn', 'ta', 'te', 'hi')`);
        await queryRunner.query(`CREATE TYPE "public"."users_identity_enum" AS ENUM('FARMER', 'BUYER', 'SUPPORT')`);
        await queryRunner.query(`CREATE TYPE "public"."users_cropnames_enum" AS ENUM('Tender Coconut', 'Turmeric', 'Banana', 'Dry Coconut')`);
        await queryRunner.query(`CREATE TYPE "public"."users_preferredpaymentmodes_enum" AS ENUM('UPI', 'CASH', 'BANK_TRANSFER')`);
        await queryRunner.query(`CREATE TYPE "public"."users_knownlanguages_enum" AS ENUM('en', 'kn', 'ta', 'te', 'hi')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "notes" text, "latitude" double precision, "longitude" double precision, "village" character varying(255), "taluk" character varying(255) NOT NULL, "district" character varying(255) NOT NULL, "pincode" character varying(6) NOT NULL, "mobileNumber" character varying NOT NULL, "language" "public"."users_language_enum" NOT NULL, "identity" "public"."users_identity_enum" NOT NULL, "fcmToken" character varying NOT NULL, "deviceId" character varying NOT NULL, "isVerified" boolean NOT NULL DEFAULT false, "cropNames" "public"."users_cropnames_enum" array NOT NULL DEFAULT '{}', "preferredPaymentModes" "public"."users_preferredpaymentmodes_enum" array NOT NULL DEFAULT '{}', "knownLanguages" "public"."users_knownlanguages_enum" array NOT NULL DEFAULT '{}', "activity" double precision NOT NULL DEFAULT '0', "score" double precision NOT NULL DEFAULT '0', "meta" jsonb NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_61dc14c8c49c187f5d08047c985" UNIQUE ("mobileNumber"), CONSTRAINT "UQ_5dbad5b81aedc54f613b55a2d73" UNIQUE ("fcmToken"), CONSTRAINT "UQ_838d3c4a6792bbb0dc90031c2c1" UNIQUE ("deviceId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."farms_weather_enum" AS ENUM('Rainy', 'Sunny', 'Cloudy', 'Stormy')`);
        await queryRunner.query(`CREATE TABLE "farms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "weather" "public"."farms_weather_enum", "lastWeatherUpdateAt" TIMESTAMP, "village" character varying(255) NOT NULL, "taluk" character varying(255) NOT NULL, "district" character varying(255) NOT NULL, "coordinates" geography(Point,4326) NOT NULL, "isVerified" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_39aff9c35006b14025bba5a43d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."crops_cropname_enum" AS ENUM('Tender Coconut', 'Turmeric', 'Banana', 'Dry Coconut')`);
        await queryRunner.query(`CREATE TYPE "public"."crops_bananavariety_enum" AS ENUM('Nendra', 'Red', 'Yelakki', 'G9')`);
        await queryRunner.query(`CREATE TYPE "public"."crops_turmericvariety_enum" AS ENUM('Salem', 'Erode', 'Sangli', 'Marathwada', 'Vizag', 'Nizamabad', 'Chamarajanagar')`);
        await queryRunner.query(`CREATE TYPE "public"."crops_drycoconutvariety_enum" AS ENUM('Naati', 'Deejay', 'Orange', 'COD', 'TNT', 'Ganga Bondam', 'Malaysian Dwarf', 'Kalparaksha', 'Chowghat Orange', 'Tiptur Tall', 'MOD', 'AGT')`);
        await queryRunner.query(`CREATE TYPE "public"."crops_tendercoconutvariety_enum" AS ENUM('Naati', 'Deejay', 'Orange', 'COD', 'TNT', 'Ganga Bondam', 'Malaysian Dwarf', 'Kalparaksha', 'Chowghat Orange', 'Tiptur Tall', 'MOD', 'AGT')`);
        await queryRunner.query(`CREATE TYPE "public"."crops_table_enum" AS ENUM('tender_coconut', 'turmeric', 'banana', 'dry_coconut', 'sunflower')`);
        await queryRunner.query(`CREATE TABLE "crops" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cropName" "public"."crops_cropname_enum" NOT NULL, "bananaVariety" "public"."crops_bananavariety_enum", "tarShape" character varying, "tarWeight" double precision, "numberOfTrees" integer, "numberOfTreesRTH" integer, "generalHarvestCycleInDays" integer, "nextHarvestDate" date, "cutCount" integer, "cutType" character varying, "isReadyToHarvest" boolean, "isVerified" boolean DEFAULT false, "images" jsonb DEFAULT '[]', "meta" jsonb DEFAULT '[]', "score" double precision DEFAULT '0', "price" double precision, "createdAt" TIMESTAMP DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "region" character varying, "turmericVariety" "public"."crops_turmericvariety_enum", "isHarvested" boolean, "isOrganic" boolean, "isPolished" boolean, "isUnpolished" boolean, "isSinglePolished" boolean, "isDoublePolished" boolean, "isRaw" boolean, "isRegular" boolean, "totalQuantity" double precision, "fingerQuantity" double precision, "bulbQuantity" double precision, "isIPM" boolean, "isOnTree" boolean, "dryCoconutVariety" "public"."crops_drycoconutvariety_enum", "numberOfNutsAvailable" integer, "isWithSemiHusk" boolean, "lastHarvestDate" date, "isWithHusk" boolean, "ageOfTree" double precision, "numberOfNuts" integer, "heightOfTree" double precision, "chutePercentage" double precision, "tenderCoconutVariety" "public"."crops_tendercoconutvariety_enum", "nutsFromLastHarvest" integer, "hasSpots" boolean, "table" "public"."crops_table_enum" NOT NULL, "farmId" uuid, CONSTRAINT "PK_098dbeb7c803dc7c08a7f02b805" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_92271ff9db7635279e6bf154d9" ON "crops" ("table") `);
        await queryRunner.query(`CREATE TYPE "public"."calls_callstatus_enum" AS ENUM('busy', 'failed', 'ringing', 'timeout', 'no-answer', 'completed', 'in-progress')`);
        await queryRunner.query(`CREATE TYPE "public"."calls_calltype_enum" AS ENUM('voice', 'conference')`);
        await queryRunner.query(`CREATE TABLE "calls" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "parentAuthId" character varying, "conferenceName" character varying, "serviceNumber" character varying NOT NULL, "callUUID" character varying, "callStatus" "public"."calls_callstatus_enum", "callType" "public"."calls_calltype_enum" DEFAULT 'voice', "direction" character varying, "routeType" character varying, "event" character varying, "hangupCause" character varying, "hangupCauseName" character varying, "hangupSource" character varying, "stirAttestation" character varying, "stirVerification" character varying, "recordingUrl" character varying, "duration" integer, "startStamp" TIMESTAMP, "endStamp" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "fromId" uuid NOT NULL, "toId" uuid NOT NULL, "agentId" uuid, "cropId" uuid, CONSTRAINT "UQ_4d29e59c98dec111e6e94931711" UNIQUE ("conferenceName"), CONSTRAINT "UQ_a5904bfb49c1122f10f6d0a9c7a" UNIQUE ("callUUID"), CONSTRAINT "PK_d9171d91f8dd1a649659f1b6a20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."channels_type_enum" AS ENUM('CHAT', 'CALL', 'VIDEO')`);
        await queryRunner.query(`CREATE TABLE "channels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."channels_type_enum" NOT NULL, "name" character varying(255), "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cropId" uuid, CONSTRAINT "PK_bc603823f3f741359c2339389f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."daily_prices_cropname_enum" AS ENUM('Tender Coconut', 'Turmeric', 'Banana', 'Dry Coconut')`);
        await queryRunner.query(`CREATE TABLE "daily_prices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cropName" "public"."daily_prices_cropname_enum" NOT NULL, "cropVariety" character varying(255), "price" double precision NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_c5bf7056ad2e0412137a7f76507" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."priority_config_entity_enum" AS ENUM('USER', 'CROP', 'FARM')`);
        await queryRunner.query(`CREATE TYPE "public"."priority_config_relation_enum" AS ENUM('USER', 'CROP', 'CROP:FARM', 'CROP:FARM:USER')`);
        await queryRunner.query(`CREATE TABLE "priority_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entity" "public"."priority_config_entity_enum" NOT NULL, "relation" "public"."priority_config_relation_enum" NOT NULL, "dependencies" json NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_287ee75525b2d54a080b5ac9b32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reservations_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "reservations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."reservations_status_enum" NOT NULL DEFAULT 'PENDING', "reservationDate" date NOT NULL, "price" double precision NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "cropId" uuid, CONSTRAINT "PK_da95cef71b617ac35dc5bcda243" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "village" character varying(255) NOT NULL, "officeName" character varying(255), "pincode" character varying(6) NOT NULL, "taluk" character varying(255) NOT NULL, "district" character varying(255) NOT NULL, "state" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deviceId" character varying NOT NULL, "refreshToken" character varying NOT NULL, "accessToken" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "UQ_b443618a8149644123d48eceed4" UNIQUE ("refreshToken"), CONSTRAINT "UQ_c6d6176d411b0b3c854df5d4d0e" UNIQUE ("accessToken"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."harvest_history_status_enum" AS ENUM('ON', 'OFF')`);
        await queryRunner.query(`CREATE TABLE "harvest_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."harvest_history_status_enum" NOT NULL, "snapshot" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cropId" uuid NOT NULL, "creatorId" uuid NOT NULL, CONSTRAINT "PK_b37d4a43a26e740686b1fa5834c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_templates_channel_enum" AS ENUM('PUSH', 'SMS', 'WHATSAPP', 'APP')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_templates_language_enum" AS ENUM('en', 'kn', 'ta', 'te', 'hi')`);
        await queryRunner.query(`CREATE TABLE "notification_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "title" character varying(255) NOT NULL, "body" text NOT NULL, "channel" "public"."notification_templates_channel_enum" NOT NULL, "language" "public"."notification_templates_language_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "creatorId" uuid NOT NULL, CONSTRAINT "UQ_4118447024198c4ac2203a8218b" UNIQUE ("name"), CONSTRAINT "PK_76f0fc48b8d057d2ae7f3a2848a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('PUSH', 'SMS', 'WHATSAPP', 'APP')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_language_enum" AS ENUM('en', 'kn', 'ta', 'te', 'hi')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "body" text NOT NULL, "channel" "public"."notifications_channel_enum" NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "language" "public"."notifications_language_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "recipientId" uuid NOT NULL, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."markets_origin_enum" AS ENUM('FARMER', 'BUYER')`);
        await queryRunner.query(`CREATE TYPE "public"."markets_cropnames_enum" AS ENUM('Tender Coconut', 'Turmeric', 'Banana', 'Dry Coconut')`);
        await queryRunner.query(`CREATE TABLE "markets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "origin" "public"."markets_origin_enum" NOT NULL, "cropNames" "public"."markets_cropnames_enum" array NOT NULL DEFAULT '{}', "coordinates" geography(Point,4326), "taluk" character varying(255) NOT NULL, "district" character varying(255) NOT NULL, "pincode" character varying(6) NOT NULL, "address" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dda44129b32f21ae9f1c28dcf99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."market_prices_cropname_enum" AS ENUM('Tender Coconut', 'Turmeric', 'Banana', 'Dry Coconut')`);
        await queryRunner.query(`CREATE TYPE "public"."market_prices_grade_enum" AS ENUM('mixed', 'single filter', 'double filter')`);
        await queryRunner.query(`CREATE TABLE "market_prices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cropName" "public"."market_prices_cropname_enum" NOT NULL, "cropVariety" character varying(255), "grade" "public"."market_prices_grade_enum", "price" double precision NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "marketId" uuid, CONSTRAINT "PK_cb959017562b6fe816d5a5c91dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_type_enum" AS ENUM('CALL_REQUEST')`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."tickets_type_enum" NOT NULL, "content" text NOT NULL, "status" "public"."tickets_status_enum" NOT NULL DEFAULT 'OPEN', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "calls_participants_users" ("callsId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_65a093a83591cb0847da0929aef" PRIMARY KEY ("callsId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1b72038d1b43a7c1a1d44b9aa2" ON "calls_participants_users" ("callsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a1c7bdb06690b9137a9273eff" ON "calls_participants_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "channels_members_users" ("channelsId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_9b1912d29ecb98dec0d3017a747" PRIMARY KEY ("channelsId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b74206541a3d6408c0894a9cb" ON "channels_members_users" ("channelsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_87a847498d21c3d00940082452" ON "channels_members_users" ("usersId") `);
        await queryRunner.query(`ALTER TABLE "farms" ADD CONSTRAINT "FK_39f1ebfd7501e560552cff6760a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crops" ADD CONSTRAINT "FK_22c38f5ca32439c43bf2a9142a2" FOREIGN KEY ("farmId") REFERENCES "farms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calls" ADD CONSTRAINT "FK_eb2a8b8f78dfccfe5b16d5c8ab6" FOREIGN KEY ("fromId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calls" ADD CONSTRAINT "FK_df9ae451da4acd607c71285817e" FOREIGN KEY ("toId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calls" ADD CONSTRAINT "FK_b1dec80edb40b218289265eccd7" FOREIGN KEY ("agentId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calls" ADD CONSTRAINT "FK_8c405ea239db0c7965d3cf18281" FOREIGN KEY ("cropId") REFERENCES "crops"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channels" ADD CONSTRAINT "FK_d73c41f244035aa887fa4a5d439" FOREIGN KEY ("cropId") REFERENCES "crops"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_prices" ADD CONSTRAINT "FK_4248ead2c0e0cca5b78e1d5b7c0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_aa0e1cc2c4f54da32bf8282154c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservations" ADD CONSTRAINT "FK_3156c8785f39c4bee17c3842d75" FOREIGN KEY ("cropId") REFERENCES "crops"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "harvest_history" ADD CONSTRAINT "FK_b23d730a36c6d6a7b6aa99e4287" FOREIGN KEY ("cropId") REFERENCES "crops"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "harvest_history" ADD CONSTRAINT "FK_42dc9b2fd7e7f6e36822da28781" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_templates" ADD CONSTRAINT "FK_ffda90ef7eabe1782740bf037e3" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_db873ba9a123711a4bff527ccd5" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "market_prices" ADD CONSTRAINT "FK_e18f8f84cc7ca173a97c28954ec" FOREIGN KEY ("marketId") REFERENCES "markets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_4bb45e096f521845765f657f5c8" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calls_participants_users" ADD CONSTRAINT "FK_1b72038d1b43a7c1a1d44b9aa2d" FOREIGN KEY ("callsId") REFERENCES "calls"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "calls_participants_users" ADD CONSTRAINT "FK_0a1c7bdb06690b9137a9273eff5" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channels_members_users" ADD CONSTRAINT "FK_2b74206541a3d6408c0894a9cb9" FOREIGN KEY ("channelsId") REFERENCES "channels"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "channels_members_users" ADD CONSTRAINT "FK_87a847498d21c3d00940082452c" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "channels_members_users" DROP CONSTRAINT "FK_87a847498d21c3d00940082452c"`);
        await queryRunner.query(`ALTER TABLE "channels_members_users" DROP CONSTRAINT "FK_2b74206541a3d6408c0894a9cb9"`);
        await queryRunner.query(`ALTER TABLE "calls_participants_users" DROP CONSTRAINT "FK_0a1c7bdb06690b9137a9273eff5"`);
        await queryRunner.query(`ALTER TABLE "calls_participants_users" DROP CONSTRAINT "FK_1b72038d1b43a7c1a1d44b9aa2d"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_4bb45e096f521845765f657f5c8"`);
        await queryRunner.query(`ALTER TABLE "market_prices" DROP CONSTRAINT "FK_e18f8f84cc7ca173a97c28954ec"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_db873ba9a123711a4bff527ccd5"`);
        await queryRunner.query(`ALTER TABLE "notification_templates" DROP CONSTRAINT "FK_ffda90ef7eabe1782740bf037e3"`);
        await queryRunner.query(`ALTER TABLE "harvest_history" DROP CONSTRAINT "FK_42dc9b2fd7e7f6e36822da28781"`);
        await queryRunner.query(`ALTER TABLE "harvest_history" DROP CONSTRAINT "FK_b23d730a36c6d6a7b6aa99e4287"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_3156c8785f39c4bee17c3842d75"`);
        await queryRunner.query(`ALTER TABLE "reservations" DROP CONSTRAINT "FK_aa0e1cc2c4f54da32bf8282154c"`);
        await queryRunner.query(`ALTER TABLE "daily_prices" DROP CONSTRAINT "FK_4248ead2c0e0cca5b78e1d5b7c0"`);
        await queryRunner.query(`ALTER TABLE "channels" DROP CONSTRAINT "FK_d73c41f244035aa887fa4a5d439"`);
        await queryRunner.query(`ALTER TABLE "calls" DROP CONSTRAINT "FK_8c405ea239db0c7965d3cf18281"`);
        await queryRunner.query(`ALTER TABLE "calls" DROP CONSTRAINT "FK_b1dec80edb40b218289265eccd7"`);
        await queryRunner.query(`ALTER TABLE "calls" DROP CONSTRAINT "FK_df9ae451da4acd607c71285817e"`);
        await queryRunner.query(`ALTER TABLE "calls" DROP CONSTRAINT "FK_eb2a8b8f78dfccfe5b16d5c8ab6"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP CONSTRAINT "FK_22c38f5ca32439c43bf2a9142a2"`);
        await queryRunner.query(`ALTER TABLE "farms" DROP CONSTRAINT "FK_39f1ebfd7501e560552cff6760a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87a847498d21c3d00940082452"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b74206541a3d6408c0894a9cb"`);
        await queryRunner.query(`DROP TABLE "channels_members_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a1c7bdb06690b9137a9273eff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b72038d1b43a7c1a1d44b9aa2"`);
        await queryRunner.query(`DROP TABLE "calls_participants_users"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_type_enum"`);
        await queryRunner.query(`DROP TABLE "market_prices"`);
        await queryRunner.query(`DROP TYPE "public"."market_prices_grade_enum"`);
        await queryRunner.query(`DROP TYPE "public"."market_prices_cropname_enum"`);
        await queryRunner.query(`DROP TABLE "markets"`);
        await queryRunner.query(`DROP TYPE "public"."markets_cropnames_enum"`);
        await queryRunner.query(`DROP TYPE "public"."markets_origin_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_language_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TABLE "notification_templates"`);
        await queryRunner.query(`DROP TYPE "public"."notification_templates_language_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_templates_channel_enum"`);
        await queryRunner.query(`DROP TABLE "harvest_history"`);
        await queryRunner.query(`DROP TYPE "public"."harvest_history_status_enum"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP TABLE "reservations"`);
        await queryRunner.query(`DROP TYPE "public"."reservations_status_enum"`);
        await queryRunner.query(`DROP TABLE "priority_config"`);
        await queryRunner.query(`DROP TYPE "public"."priority_config_relation_enum"`);
        await queryRunner.query(`DROP TYPE "public"."priority_config_entity_enum"`);
        await queryRunner.query(`DROP TABLE "daily_prices"`);
        await queryRunner.query(`DROP TYPE "public"."daily_prices_cropname_enum"`);
        await queryRunner.query(`DROP TABLE "channels"`);
        await queryRunner.query(`DROP TYPE "public"."channels_type_enum"`);
        await queryRunner.query(`DROP TABLE "calls"`);
        await queryRunner.query(`DROP TYPE "public"."calls_calltype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."calls_callstatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92271ff9db7635279e6bf154d9"`);
        await queryRunner.query(`DROP TABLE "crops"`);
        await queryRunner.query(`DROP TYPE "public"."crops_table_enum"`);
        await queryRunner.query(`DROP TYPE "public"."crops_tendercoconutvariety_enum"`);
        await queryRunner.query(`DROP TYPE "public"."crops_drycoconutvariety_enum"`);
        await queryRunner.query(`DROP TYPE "public"."crops_turmericvariety_enum"`);
        await queryRunner.query(`DROP TYPE "public"."crops_bananavariety_enum"`);
        await queryRunner.query(`DROP TYPE "public"."crops_cropname_enum"`);
        await queryRunner.query(`DROP TABLE "farms"`);
        await queryRunner.query(`DROP TYPE "public"."farms_weather_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_knownlanguages_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_preferredpaymentmodes_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_cropnames_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_identity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_language_enum"`);
    }

}
